/**
 * The character catalog (owner decision 2026-10-05): 20 free companions per category, all drawn
 * in the roster's chibi style and animated like Chalito (five drawings each). The original six
 * roster characters are spread into their categories. Prompts feed generate-roster.ts.
 */
export const CATEGORIES = [
  "animals",
  "people",
  "food",
  "sports",
  "professions",
  "emotions",
  "objects",
  "mexican",
  "fantasy",
  "space",
  "seasons",
] as const;
export type Category = (typeof CATEGORIES)[number];

export interface CatalogCharacter {
  id: string;
  category: Category;
  name: { es: string; en: string };
  blurb: { es: string; en: string };
  /** Design description sent to the image model (style is appended by the generator). */
  prompt: string;
}

const c = (
  category: Category,
  id: string,
  es: string,
  en: string,
  blurbEs: string,
  blurbEn: string,
  prompt: string,
): CatalogCharacter => ({ id, category, name: { es, en }, blurb: { es: blurbEs, en: blurbEn }, prompt });

export const CATALOG: readonly CatalogCharacter[] = [
  // Animals: the five original animal companions plus fifteen new ones.
  c("animals", "bruno", "Bruno", "Bruno", "Un osito tranquilo y paciente.", "A calm, patient bear.",
    "Bruno, a chubby honey-brown teddy bear with a cream muzzle and belly patch, small round ears, a little red scarf"),
  c("animals", "luna", "Luna", "Luna", "Una gatita curiosa.", "A curious kitten.",
    "Luna, a fluffy grey kitten with big green eyes, white paws and chest, a pink nose, a thin crescent-moon collar charm"),
  c("animals", "tito", "Tito", "Tito", "Un búho atento a todo.", "An owl who notices everything.",
    "Tito, a round little owl with soft brown and cream feathers, huge amber eyes, tiny tufted ears, small wings"),
  c("animals", "canela", "Canela", "Canela", "Una zorrita lista y rápida.", "A quick, clever fox.",
    "Canela, a small orange fox with a white-tipped bushy tail, white chest, dark paws, big curious eyes"),
  c("animals", "nube", "Nube", "Nube", "Una conejita suave y alegre.", "A soft, cheerful bunny.",
    "Nube, a fluffy white bunny with long floppy ears with pink insides, a pink nose, a round cotton tail, sky-blue eyes"),
  c("animals", "firulais", "Firulais", "Firulais", "Un perrito leal y juguetón.", "A loyal, playful puppy.",
    "Firulais, a small tan and white puppy with floppy ears, a wagging tail, a blue collar with a round gold tag, a happy pink tongue"),
  c("animals", "bambu", "Bambú", "Bambu", "Un panda que nunca tiene prisa.", "A panda who's never in a hurry.",
    "Bambu, a round black-and-white baby panda holding a small green bamboo sprig, soft fuzzy fur, sleepy kind eyes"),
  c("animals", "pinguino", "Pingo", "Pingo", "Un pingüino elegante y torpe.", "A dapper, clumsy penguin.",
    "Pingo, a little emperor-style penguin chick with a sleek black back, white belly, orange beak and feet, a tiny red bow tie"),
  c("animals", "koala", "Koko", "Koko", "Una koala que da los mejores abrazos.", "A koala who gives the best hugs.",
    "Koko, a fluffy grey koala with big round white-tufted ears, a large dark oval nose, a cream belly, a small eucalyptus leaf"),
  c("animals", "axo", "Axo", "Axo", "Un ajolote que siempre sonríe.", "An axolotl who's always smiling.",
    "Axo, a pink Mexican axolotl standing upright, feathery pink-magenta gill fronds on both sides of the head, a wide gentle smile, tiny hands, a short tail"),
  c("animals", "tortu", "Tortu", "Tortu", "Una tortuga sabia y sin estrés.", "A wise, stress-free turtle.",
    "Tortu, a small green tortoise standing upright with a domed olive shell with hexagon pattern, round glasses, a calm wise smile"),
  c("animals", "trompi", "Trompi", "Trompi", "Una elefantita que nunca olvida.", "A little elephant who never forgets.",
    "Trompi, a baby elephant with soft lavender-grey skin, big floppy ears with pink insides, a curled-up trunk, a small yellow flower behind one ear"),
  c("animals", "jirafa", "Jacinta", "Jacinta", "Una jirafa que ve todo desde arriba.", "A giraffe who sees it all from above.",
    "Jacinta, a young giraffe with a short chibi neck, golden-yellow fur with orange-brown patches, small horn ossicones, long eyelashes"),
  c("animals", "leo", "Leo", "Leo", "Un leoncito valiente.", "A brave little lion.",
    "Leo, a lion cub with golden fur, a fluffy round orange mane, a tufted tail, a confident friendly grin"),
  c("animals", "chango", "Chango", "Chango", "Un monito travieso.", "A mischievous little monkey.",
    "Chango, a small brown monkey with a peach face and belly, big round ears, a long curly tail, holding a banana"),
  c("animals", "rana", "Rita", "Rita", "Una ranita brincona.", "A bouncy little frog.",
    "Rita, a bright green frog standing upright, big round eyes on top of the head, a pale yellow belly, a tiny lily-pad hat"),
  c("animals", "pulpo", "Pulpi", "Pulpi", "Un pulpo que hace ocho cosas a la vez.", "An octopus who multitasks with eight arms.",
    "Pulpi, a round coral-orange octopus with eight curly tentacles, light spots on the head, big friendly eyes"),
  c("animals", "cochi", "Cochi", "Cochi", "Una cerdita alegre y glotona.", "A cheerful, foodie piglet.",
    "Cochi, a round pink piglet standing upright, a curly tail, a big snout, small floppy ears, a little blue overall strap"),
  c("animals", "pato", "Paco", "Paco", "Un patito con mucha personalidad.", "A duckling with big personality.",
    "Paco, a fluffy yellow duckling with an orange bill and feet, a tiny sailor cap"),
  c("animals", "perezoso", "Lento", "Lento", "Un perezoso que te recuerda descansar.", "A sloth who reminds you to rest.",
    "Lento, a sloth with shaggy light-brown fur, a cream face with dark eye patches, a sleepy peaceful smile, long curved claws, hugging a small pillow"),
  // People: Chalito leads; a mix of ages, looks and styles.
  c("people", "chalito", "Chalito", "Chalito", "Tu compañero de siempre.", "Your everyday companion.",
    "Chalito, a small human-ish companion: a cheerful round-faced kid-like figure in an oversized teal hoodie with the hood down, short messy dark hair, big warm brown eyes, rosy cheeks, a tiny glowing yellow star clip in the hair"),
  c("people", "abuela", "Doña Chela", "Granny Chela", "Una abuelita con consejos para todo.", "A granny with advice for everything.",
    "Doña Chela, a sweet chubby grandmother with a grey hair bun, round glasses, a lilac cardigan over a floral dress, holding a mug of hot chocolate"),
  c("people", "abuelo", "Don Beto", "Grandpa Beto", "Un abuelo con mil historias.", "A grandpa with a thousand stories.",
    "Don Beto, a kind grandfather with a white mustache, a flat cap, a brown vest over a white shirt, suspenders, a wooden cane"),
  c("people", "bebe", "Bebé Lalo", "Baby Lalo", "Un bebé que todo lo descubre.", "A baby discovering everything.",
    "Bebe Lalo, a chubby toddler in a light-blue onesie with a pacifier clipped on, a single curl of hair on top, big curious eyes"),
  c("people", "sofi", "Sofi", "Sofi", "Una niña con energía infinita.", "A girl with endless energy.",
    "Sofi, a lively young girl with two curly pigtails tied with yellow ribbons, a red t-shirt with a star, denim shorts, sneakers"),
  c("people", "skater", "Max", "Max", "Un skater relajado.", "A laid-back skater.",
    "Max, a teen skater with a backwards orange cap, a loose grey t-shirt, baggy cargo shorts, holding a skateboard"),
  c("people", "gamer", "Pixel", "Pixel", "Una gamer que nunca pierde.", "A gamer who never loses.",
    "Pixel, a young woman gamer with short purple hair, big headphones around the neck, a black hoodie with a pixel heart, holding a game controller"),
  c("people", "artista", "Pinta", "Pinta", "Una artista llena de color.", "An artist full of color.",
    "Pinta, a young artist with a short wavy red bob and a black beret, a paint-splattered blue apron, a paintbrush tucked behind the ear, holding a colorful palette"),
  c("people", "rockero", "Rocko", "Rocko", "Un rockero de buen corazón.", "A rocker with a big heart.",
    "Rocko, a rocker with spiky black hair, a black leather jacket with pins, ripped jeans, an electric guitar slung on the back"),
  c("people", "bailarina", "Bela", "Bela", "Una bailarina elegante.", "A graceful dancer.",
    "Bela, a ballerina with a neat hair bun, a pink tutu and leotard, ballet slippers, standing on tiptoe with arms in a soft curve"),
  c("people", "hipster", "Brayan", "Brayan", "Un barbón amante del café.", "A bearded coffee lover.",
    "Brayan, a young man with a big neat brown beard, a beanie, a plaid flannel shirt, round glasses, holding a takeaway coffee cup"),
  c("people", "mama", "Mamá Lupita", "Mom Lupita", "Una mamá que siempre te apoya.", "A mom who always has your back.",
    "Mama Lupita, a warm young mother with a long dark braid, a mustard sweater, jeans, a tote bag, a loving smile"),
  c("people", "papa", "Papá Toño", "Dad Toño", "Un papá con chistes malos.", "A dad with terrible jokes.",
    "Papa Tono, a cheerful dad with short dark hair, a light stubble, a polo shirt, khaki shorts, sandals, a grill spatula"),
  c("people", "estudiante", "Valeria", "Valeria", "Una estudiante aplicada.", "A dedicated student.",
    "Valeria, a university student with a high ponytail, a green sweater, a backpack, holding a stack of books"),
  c("people", "deportista", "Diego", "Diego", "Un chavo que no para de moverse.", "A guy always on the move.",
    "Diego, a sporty young man in a tracksuit with white stripes, a sweatband on the forehead, running shoes, a water bottle"),
  c("people", "nerd", "Memo", "Memo", "Un genio de las computadoras.", "A computer whiz.",
    "Memo, a nerdy boy with big square glasses, a neat side part, a sweater vest over a collared shirt, holding a laptop"),
  c("people", "influencer", "Kimmy", "Kimmy", "Una influencer siempre en tendencia.", "An influencer always on trend.",
    "Kimmy, a trendy young woman with long wavy pink-blonde hair, sunglasses on top of the head, a crop jacket, holding a phone for a selfie"),
  c("people", "viajero", "Tomás", "Tomas", "Un mochilero que conoce el mundo.", "A backpacker who's seen the world.",
    "Tomas, a backpacker with a big hiking backpack, a bucket hat, a camera around the neck, a map in hand, hiking boots"),
  c("people", "dj", "DJ Neón", "DJ Neon", "Una DJ que pone ambiente.", "A DJ who sets the vibe.",
    "DJ Neon, a DJ with a sleek black bob with a neon-blue streak, big glowing headphones, a sparkly jacket, one hand raised"),
  c("people", "rapero", "MC Chuy", "MC Chuy", "Un rapero con rimas para todo.", "A rapper with a rhyme for everything.",
    "MC Chuy, a rapper with a gold chain, an oversized red hoodie, a flat-brim cap, holding a microphone"),

  // Food: friendly food characters with faces, little arms and legs.
  c("food", "taquito", "Taquito", "Taquito", "Un taco al pastor con mucho sabor.", "A flavor-packed al pastor taco.",
    "Taquito, a cute folded corn tortilla taco character filled with al pastor meat, pineapple, cilantro and onion, with a face, tiny arms and legs"),
  c("food", "concha", "Conchita", "Conchita", "Un pan dulce de concha.", "A sweet concha bun.",
    "Conchita, a round Mexican concha sweet bun character with a pink sugar shell pattern on top, a face, tiny arms and legs"),
  c("food", "aguacate", "Aguacatín", "Avocadito", "Un aguacate buena onda.", "A chill avocado.",
    "Avocadito, a halved avocado character with a big round brown pit as the belly, green skin, a face, tiny arms and legs"),
  c("food", "elote", "Elotito", "Elotito", "Un elote con mayonesa y chile.", "A corn cob with mayo and chili.",
    "Elotito, a corn-on-the-cob character on a stick covered in mayo, cheese and red chili powder, a face, tiny arms"),
  c("food", "pizza", "Peperoni", "Peperoni", "Una rebanada de pizza feliz.", "A happy pizza slice.",
    "Peperoni, a pizza slice character with melty cheese, pepperoni circles, a golden crust on top, a face, tiny arms and legs"),
  c("food", "sushi", "Maki", "Maki", "Un sushi pequeñito y ordenado.", "A tiny, tidy sushi roll.",
    "Maki, a sushi roll character with a seaweed wrap, white rice and a salmon-orange center, a face, tiny arms and legs"),
  c("food", "dona", "Dony", "Dony", "Una dona con chispitas.", "A sprinkled donut.",
    "Dony, a round donut character with pink frosting and rainbow sprinkles, a face, tiny arms and legs"),
  c("food", "helado", "Nieve", "Scoop", "Un helado que nunca se derrite.", "An ice cream that never melts.",
    "Scoop, an ice cream cone character with a strawberry scoop on top, a cherry, a waffle cone body, a face, tiny arms"),
  c("food", "hamburguesa", "Burgui", "Burgy", "Una hamburguesa bien armada.", "A well-stacked burger.",
    "Burgy, a burger character with a sesame bun, lettuce, cheese and a patty, a face on the patty, tiny arms and legs"),
  c("food", "papas", "Papita", "Fry Guy", "Unas papas fritas crujientes.", "Crispy french fries.",
    "Fry Guy, a red carton of golden french fries with a face on the carton, tiny arms and legs"),
  c("food", "fresa", "Fresi", "Berry", "Una fresa dulce y tierna.", "A sweet strawberry.",
    "Berry, a red strawberry character with seeds, a green leafy crown, a face, tiny arms and legs"),
  c("food", "platano", "Platanito", "Banano", "Un plátano siempre de buenas.", "A banana always in a good mood.",
    "Banano, a yellow banana character half peeled at the top like a hairdo, a face, tiny arms and legs"),
  c("food", "tamal", "Tamalito", "Tamalito", "Un tamal calientito.", "A warm little tamale.",
    "Tamalito, a tamale character wrapped in a corn husk open at the top showing yellow masa, a face, tiny arms and legs"),
  c("food", "churro", "Churri", "Churro", "Un churro con azúcar y canela.", "A cinnamon-sugar churro.",
    "Churro, a long golden ridged churro character dusted with cinnamon sugar, a face, tiny arms and legs"),
  c("food", "cafe", "Cafecito", "Coffee Cup", "Un cafecito que te despierta.", "A coffee to wake you up.",
    "Coffee Cup, a steaming mug of coffee with a latte-art heart, a face on the mug, tiny arms and legs"),
  c("food", "galleta", "Galletón", "Cookie", "Una galleta con chispas.", "A chocolate chip cookie.",
    "Cookie, a round chocolate chip cookie character, golden brown, a face, tiny arms and legs"),
  c("food", "pan", "Bolillo", "Bolillo", "Un bolillo recién horneado.", "A fresh-baked bread roll.",
    "Bolillo, a crusty Mexican bolillo bread roll character with a slit on top, a face, tiny arms and legs"),
  c("food", "sandia", "Sandi", "Melony", "Una sandía refrescante.", "A refreshing watermelon.",
    "Melony, a watermelon slice character with red flesh, black seeds and a green rind, a face, tiny arms and legs"),
  c("food", "brocoli", "Brócoli", "Brocco", "Un brócoli fuerte y sano.", "A strong, healthy broccoli.",
    "Brocco, a broccoli floret character with a bushy green top like hair, a light green stalk body, a face, tiny arms and legs"),
  c("food", "pastel", "Pastelito", "Cupcake", "Un pastelito de fiesta.", "A party cupcake.",
    "Cupcake, a cupcake character with swirly vanilla frosting, a cherry and sprinkles, a striped paper cup body, a face, tiny arms"),

  // Sports: athletes and sporty mascots.
  c("sports", "futbolista", "Golazo", "Golazo", "Un futbolista que celebra cada gol.", "A footballer who celebrates every goal.",
    "Golazo, a soccer player kid in a green jersey with number 10, white shorts, cleats, a soccer ball under one foot"),
  c("sports", "basquet", "Clavada", "Dunk", "Una basquetbolista que salta alto.", "A basketball player who jumps high.",
    "Dunk, a basketball player girl in an orange jersey, a headband, high-top sneakers, spinning a basketball on one finger"),
  c("sports", "beisbol", "Jonrón", "Homer", "Un beisbolista de grandes ligas.", "A big-league baseball player.",
    "Homer, a baseball player in a pinstriped uniform and cap, a baseball glove, a wooden bat over the shoulder"),
  c("sports", "tenista", "Raqueta", "Ace", "Una tenista con saque imparable.", "A tennis player with an unstoppable serve.",
    "Ace, a tennis player girl in a white tennis outfit, a visor, holding a tennis racket and a yellow ball"),
  c("sports", "nadador", "Delfín", "Splash", "Un nadador veloz.", "A speedy swimmer.",
    "Splash, a swimmer with a blue swim cap, goggles on the forehead, a swimsuit, a towel over the shoulder"),
  c("sports", "boxeador", "Campeón", "Champ", "Un boxeador con gran corazón.", "A boxer with a big heart.",
    "Champ, a boxer in red boxing gloves, red shorts with a gold belt, a confident friendly pose"),
  c("sports", "luchador", "Místico", "Mystic", "Un luchador enmascarado.", "A masked wrestler.",
    "Mystic, a chibi Mexican lucha libre wrestler with a silver and blue mask, a cape, wrestling boots, a flexing pose"),
  c("sports", "ciclista", "Pedalín", "Pedal", "Un ciclista que no se cansa.", "A cyclist who never tires.",
    "Pedal, a cyclist in a yellow cycling jersey, a helmet, cycling shorts, standing beside a small bicycle"),
  c("sports", "corredora", "Rayo", "Bolt", "Una corredora rapidísima.", "A super-fast runner.",
    "Bolt, a runner girl with a ponytail, a race bib number on a tank top, running shorts, running shoes, ready-to-run pose"),
  c("sports", "gimnasta", "Gimi", "Gymmy", "Una gimnasta flexible.", "A flexible gymnast.",
    "Gymmy, a gymnast girl in a sparkly purple leotard, a ribbon wand swirling around her"),
  c("sports", "surfista", "Ola", "Wave", "Un surfista con buena vibra.", "A surfer with good vibes.",
    "Wave, a surfer with sun-bleached hair, board shorts with hibiscus print, holding a surfboard"),
  c("sports", "patinadora", "Patín", "Skates", "Una patinadora sobre hielo.", "An ice skater.",
    "Skates, a figure skater girl in a light-blue sparkly dress, white ice skates, a graceful twirl pose"),
  c("sports", "karateca", "Kata", "Kata", "Un karateca disciplinado.", "A disciplined karateka.",
    "Kata, a karate kid in a white gi with a black belt, a headband, a karate stance"),
  c("sports", "golfista", "Birdie", "Birdie", "Un golfista muy tranquilo.", "A very calm golfer.",
    "Birdie, a golfer in a argyle sweater vest, a flat cap, holding a golf club, a golf ball at the feet"),
  c("sports", "portero", "Atajadas", "Keeper", "Un portero que todo lo para.", "A goalkeeper who stops everything.",
    "Keeper, a soccer goalkeeper in a bright yellow long-sleeve jersey, big padded gloves, holding a soccer ball"),
  c("sports", "voleibol", "Remate", "Spike", "Una voleibolista con gran remate.", "A volleyball player with a mighty spike.",
    "Spike, a volleyball player girl in a jersey and knee pads, holding a white and blue volleyball"),
  c("sports", "escalador", "Cumbre", "Summit", "Un escalador sin miedo.", "A fearless climber.",
    "Summit, a rock climber with a helmet, a harness with carabiners, a coiled rope over the shoulder, chalky hands"),
  c("sports", "ajedrez", "Jaque", "Check", "Una ajedrecista que piensa todo.", "A chess player who thinks it all through.",
    "Check, a chess player girl with round glasses, a neat sweater, holding a big white knight chess piece"),
  c("sports", "yoga", "Zen", "Zen", "Una yogui en calma.", "A calm yogi.",
    "Zen, a yoga practitioner in leggings and a tank top, a hair bun, standing in tree pose on a rolled-out mat"),
  c("sports", "futbolamericano", "Touchdown", "Touchdown", "Un jugador de americano.", "An American football player.",
    "Touchdown, an American football player with a helmet, big shoulder pads, a jersey, holding a football"),

  // Professions.
  c("professions", "doctora", "Dra. Salud", "Dr. Health", "Una doctora que te cuida.", "A doctor who looks after you.",
    "Dr. Health, a young woman doctor with a long dark ponytail, a white coat, a stethoscope around the neck, a clipboard, a kind smile"),
  c("professions", "enfermero", "Enfermero Ramón", "Nurse Ramon", "Un enfermero atento.", "An attentive nurse.",
    "Nurse Ramon, a male nurse in teal scrubs, a lanyard badge, holding a small first-aid kit"),
  c("professions", "abogada", "Lic. Justa", "Attorney Justa", "Una abogada que defiende tus derechos.", "A lawyer who defends your rights.",
    "Attorney Justa, a lawyer in a navy suit with a neat bun, holding a briefcase and a small scales-of-justice emblem pin"),
  c("professions", "bombero", "Bombero Fuego", "Firefighter Blaze", "Un bombero valiente.", "A brave firefighter.",
    "Firefighter Blaze, a firefighter in a red helmet and yellow-striped fire suit, holding a fire hose"),
  c("professions", "policia", "Oficial Paz", "Officer Paz", "Una oficial que protege.", "An officer who protects.",
    "Officer Paz, a friendly police officer in a blue uniform and cap with a star badge, a whistle"),
  c("professions", "chef", "Chef Pepe", "Chef Pepe", "Un chef con recetas secretas.", "A chef with secret recipes.",
    "Chef Pepe, a chef with a tall white toque, a white double-breasted jacket, a curly mustache, holding a wooden spoon"),
  c("professions", "maestra", "Maestra Rosy", "Teacher Rosy", "Una maestra paciente.", "A patient teacher.",
    "Teacher Rosy, a teacher with glasses, a cardigan, holding a book and a pointer, an apple on the book"),
  c("professions", "astronauta", "Astro", "Astro", "Un astronauta curioso.", "A curious astronaut.",
    "Astro, an astronaut in a white space suit with a round helmet visor up, mission patches, a small flag patch"),
  c("professions", "cientifica", "Dra. Átomo", "Dr. Atom", "Una científica que experimenta.", "A scientist who experiments.",
    "Dr. Atom, a scientist in a lab coat with safety goggles on her head, holding a bubbling green flask"),
  c("professions", "programador", "Dev", "Dev", "Un programador que arregla bugs.", "A programmer who squashes bugs.",
    "Dev, a programmer in a hoodie with a laptop under the arm, a coffee mug, a lanyard, slightly messy hair"),
  c("professions", "constructor", "Ingeniero Toño", "Builder Tony", "Un constructor que hace de todo.", "A builder who can make anything.",
    "Builder Tony, a construction worker in a yellow hard hat, an orange safety vest, a tool belt, holding a wrench"),
  c("professions", "piloto", "Capitana Nubes", "Captain Sky", "Una piloto de avión.", "An airline pilot.",
    "Captain Sky, an airline pilot in a navy uniform with gold stripes, a pilot cap with wings badge, aviator sunglasses"),
  c("professions", "veterinaria", "Vet Mimi", "Vet Mimi", "Una veterinaria que ama a los animales.", "A vet who loves animals.",
    "Vet Mimi, a veterinarian in light-green scrubs, a stethoscope, holding a small puppy"),
  c("professions", "cartero", "Cartero Lucho", "Mailman Lucho", "Un cartero siempre puntual.", "An always-punctual mail carrier.",
    "Mailman Lucho, a mail carrier with a blue cap, a satchel full of letters, holding an envelope"),
  c("professions", "granjero", "Don Pancho", "Farmer Pancho", "Un granjero trabajador.", "A hardworking farmer.",
    "Farmer Pancho, a farmer with a straw hat, denim overalls, a plaid shirt, holding a basket of vegetables"),
  c("professions", "dentista", "Dra. Sonrisa", "Dr. Smile", "Una dentista que cuida tu sonrisa.", "A dentist who cares for your smile.",
    "Dr. Smile, a young woman dentist with curly brown hair in a bun, a white coat and mask pulled down, holding a giant toothbrush, a sparkling smile"),
  c("professions", "mecanico", "Mecánico Nacho", "Mechanic Nacho", "Un mecánico que lo arregla todo.", "A mechanic who fixes everything.",
    "Mechanic Nacho, a mechanic in grease-stained blue coveralls, a cap, a wrench, a smudge on the cheek"),
  c("professions", "detective", "Detective Lupa", "Detective Lens", "Una detective que resuelve misterios.", "A detective who solves mysteries.",
    "Detective Lens, a detective in a tan trench coat and deerstalker hat, holding a magnifying glass"),
  c("professions", "fotografa", "Foto Fer", "Photo Fer", "Una fotógrafa que captura momentos.", "A photographer who captures moments.",
    "Photo Fer, a photographer with a big camera, a camera strap, a vest with pockets, a beanie"),
  c("professions", "contador", "Contador Rubén", "Accountant Ruben", "Un contador que cuadra todo.", "An accountant who balances everything.",
    "Accountant Ruben, an accountant in a shirt and tie with a calculator, a pencil behind the ear, glasses"),

  // Emotions: little blob creatures that each embody one feeling (the emotion drawings still vary them).
  c("emotions", "alegria", "Alegría", "Joy", "Pura felicidad.", "Pure happiness.",
    "Joy, a round sunny-yellow blob creature with sparkles around it, tiny arms and feet, a radiant personality"),
  c("emotions", "calma", "Calma", "Calm", "Respira profundo.", "Take a deep breath.",
    "Calm, a soft pale-blue cloud-like blob creature with a gentle face, tiny arms and feet, floating little bubbles"),
  c("emotions", "amor", "Amor", "Love", "Todo corazón.", "All heart.",
    "Love, a heart-shaped pink creature with tiny arms and feet, little floating hearts around it"),
  c("emotions", "valentia", "Valentía", "Courage", "Nada lo detiene.", "Nothing stops it.",
    "Courage, a round orange blob creature wearing a tiny red superhero cape, a little lightning mark on its chest"),
  c("emotions", "curiosidad", "Curiosidad", "Curiosity", "Siempre pregunta por qué.", "Always asking why.",
    "Curiosity, a teal blob creature with one antenna ending in a question-mark curl, big inquisitive eyes, tiny arms and feet"),
  c("emotions", "esperanza", "Esperanza", "Hope", "Siempre ve la luz.", "Always sees the light.",
    "Hope, a small glowing soft-green blob creature holding a tiny sprouting plant, a gentle warm glow"),
  c("emotions", "gratitud", "Gratitud", "Gratitude", "Agradece todo.", "Thankful for everything.",
    "Gratitude, a warm peach-colored blob creature with hands together, a small golden halo of light"),
  c("emotions", "orgullo", "Orgullo", "Pride", "Celebra tus logros.", "Celebrates your wins.",
    "Pride, a purple blob creature with a small gold medal around its neck, chest puffed out"),
  c("emotions", "nervios", "Nervios", "Jitters", "Un poquito nervioso.", "A little bit nervous.",
    "Jitters, a small lime-green blob creature with wobbly outline lines, a tiny sweat drop, fidgeting hands"),
  c("emotions", "enojo", "Enojo", "Grumpy", "Gruñón pero buena onda.", "Grumpy but good-hearted.",
    "Grumpy, a round red blob creature with tiny steam puffs on its head, crossed arms, small stubby feet"),
  c("emotions", "tristeza", "Melancolía", "Blue", "Te acompaña en días grises.", "Keeps you company on grey days.",
    "Blue, a teardrop-shaped soft blue creature with tiny arms and feet, a little raincloud hat"),
  c("emotions", "sorpresa", "Sorpresa", "Wow", "Todo le asombra.", "Amazed by everything.",
    "Wow, a star-shaped bright yellow-orange creature with tiny arms and feet, little exclamation sparkles around it"),
  c("emotions", "sueno", "Sueño", "Sleepy", "Siempre lista para una siesta.", "Always ready for a nap.",
    "Sleepy, a lavender blob creature in a striped nightcap, holding a tiny pillow, little floating Z letters shapes"),
  c("emotions", "risa", "Risa", "Giggles", "No para de reír.", "Can't stop laughing.",
    "Giggles, a bubbly bright-pink blob creature with rosy cheeks, holding its belly, tiny musical notes around"),
  c("emotions", "paz", "Paz", "Peace", "Tranquilidad total.", "Total serenity.",
    "Peace, a white dove-like round creature with tiny wings, holding a small olive branch, a serene look"),
  c("emotions", "emocion", "Emoción", "Hype", "¡Súper emocionada!", "Super hyped!",
    "Hype, a bright electric-blue blob creature with little confetti bursting around it, tiny arms raised"),
  c("emotions", "timidez", "Timidez", "Shy", "Tímida pero tierna.", "Shy but sweet.",
    "Shy, a small pastel-pink blob creature partly hiding behind its own tiny hands, blushing cheeks"),
  c("emotions", "confianza", "Confianza", "Confidence", "Cree en ti.", "Believes in you.",
    "Confidence, a teal blob creature wearing tiny cool sunglasses, a thumbs up, a little crown"),
  c("emotions", "nostalgia", "Nostalgia", "Nostalgia", "Recuerda los buenos tiempos.", "Remembers the good times.",
    "Nostalgia, a sepia-toned soft brown blob creature holding a tiny old photo, a gentle wistful look"),
  c("emotions", "ternura", "Ternura", "Tenderness", "Pura ternura.", "Pure sweetness.",
    "Tenderness, a fluffy cream-colored round creature with tiny bunny-like ears, holding a small heart"),

  // Objects: everyday things come to life.
  c("objects", "lampara", "Lamparita", "Lampy", "Una lámpara con ideas brillantes.", "A lamp with bright ideas.",
    "Lampy, a little desk lamp character with a glowing yellow bulb, a face on the lampshade, tiny arms and legs"),
  c("objects", "taza", "Tacita", "Mugsy", "Una taza que te acompaña.", "A mug that keeps you company.",
    "Mugsy, a white ceramic mug character with a blue stripe, a face, tiny arms and legs, a little steam swirl"),
  c("objects", "libro", "Librito", "Booky", "Un libro lleno de historias.", "A book full of stories.",
    "Booky, a red hardcover book character, slightly open, a face on the cover, tiny arms and legs"),
  c("objects", "lapiz", "Lápiz", "Pencil", "Un lápiz que dibuja sueños.", "A pencil that draws dreams.",
    "Pencil, a yellow pencil character with a pink eraser top, a sharpened tip as the feet, a face, tiny arms"),
  c("objects", "reloj", "Tic Tac", "Tick Tock", "Un reloj siempre a tiempo.", "A clock that's always on time.",
    "Tick Tock, a round red alarm clock character with two bells on top, a face on the dial, tiny arms and legs"),
  c("objects", "celular", "Cel", "Phoney", "Un celular siempre conectado.", "An always-online phone.",
    "Phoney, a smartphone character with a face on the screen, a colorful case, tiny arms and legs"),
  c("objects", "audifonos", "Audi", "Beats", "Unos audífonos con ritmo.", "Headphones with rhythm.",
    "Beats, a pair of over-ear headphones character, with a face on the headband, music notes around"),
  c("objects", "trompo", "Trompo", "Spinny", "Un trompo mexicano que no para.", "A Mexican spinning top that never stops.",
    "Spinny, a colorful wooden Mexican trompo spinning top character with painted stripes, a string, a face, tiny arms"),
  c("objects", "mochila", "Mochi", "Packy", "Una mochila lista para la aventura.", "A backpack ready for adventure.",
    "Packy, a green school backpack character with pockets, a face on the front, the straps as arms, tiny feet"),
  c("objects", "paraguas", "Paragüitas", "Brolly", "Un paraguas que te protege.", "An umbrella that protects you.",
    "Brolly, an open yellow umbrella character with a curved handle as the leg, a face under the canopy, tiny arms"),
  c("objects", "camara", "Clic", "Clicky", "Una cámara que guarda recuerdos.", "A camera that keeps memories.",
    "Clicky, a retro instant camera character with a big lens as a nose, a face, tiny arms and legs, a little photo coming out"),
  c("objects", "planta", "Maceta", "Sprout", "Una plantita que crece contigo.", "A little plant that grows with you.",
    "Sprout, a terracotta flowerpot character with a small green succulent growing on top, a face on the pot, tiny arms and legs"),
  c("objects", "vela", "Velita", "Candle", "Una velita que ilumina.", "A little candle that lights the way.",
    "Candle, a short white candle character with a warm flickering flame on top, a face, tiny arms"),
  c("objects", "globo", "Globito", "Balloony", "Un globo que te alegra.", "A balloon that cheers you up.",
    "Balloony, a round red party balloon character with a curly string, a face, tiny arms"),
  c("objects", "consola", "Joystick", "Joystick", "Un control listo para jugar.", "A controller ready to play.",
    "Joystick, a game controller character with colorful buttons, a face between the joysticks, tiny arms and legs"),
  c("objects", "tostadora", "Tosti", "Toasty", "Una tostadora con chispa.", "A toaster with spark.",
    "Toasty, a shiny silver toaster character with two slices of toast popping out like hair, a face, tiny arms and legs"),
  c("objects", "calcetin", "Calce", "Sock", "Un calcetín que perdió a su par.", "A sock looking for its pair.",
    "Sock, a striped colorful sock character with a face, tiny arms, standing on its heel"),
  c("objects", "cubo", "Cubi", "Cuby", "Un cubo mágico ingenioso.", "A clever puzzle cube.",
    "Cuby, a colorful puzzle cube character with a face on the front, tiny arms and legs"),
  c("objects", "lata", "Latita", "Canny", "Una lata de refresco burbujeante.", "A fizzy soda can.",
    "Canny, a red soda can character with little fizz bubbles, a face, tiny arms and legs"),
  c("objects", "dado", "Dadito", "Dicey", "Un dado con suerte.", "A lucky die.",
    "Dicey, a white rounded dice character with black dots, a face on the front side, tiny arms and legs"),

  // Mexican culture.
  c("mexican", "mariachi", "Mariachi Chente", "Mariachi Chente", "Un mariachi que canta con el alma.", "A mariachi who sings from the heart.",
    "Mariachi Chente, a mariachi in a black charro suit with silver buttons, a big sombrero, holding a guitar"),
  c("mexican", "catrina", "Catrina", "Catrina", "La catrina más elegante.", "The most elegant Catrina.",
    "Catrina, a friendly cute Catrina with a sugar-skull painted face, a big flowered hat, a long elegant purple dress, marigold flowers"),
  c("mexican", "alebrije", "Alebrije", "Alebrije", "Un alebrije de mil colores.", "A thousand-color alebrije.",
    "Alebrije, a fantastical Oaxacan alebrije creature, part jaguar part dragon, covered in bright painted patterns and colorful wings"),
  c("mexican", "charro", "Charro Lalo", "Charro Lalo", "Un charro de gran estilo.", "A charro with great style.",
    "Charro Lalo, a charro horseman in a decorated suede suit, a wide embroidered sombrero, a lasso"),
  c("mexican", "adelita", "Adelita", "Adelita", "Una adelita valiente.", "A brave Adelita.",
    "Adelita, a brave revolutionary-era woman with long braids, a rebozo shawl, a long skirt, a determined smile"),
  c("mexican", "jarocha", "Jarocha", "Jarocha", "Bailando son jarocho.", "Dancing son jarocho.",
    "Jarocha, a dancer in a white lace Veracruz dress, a red flower in the hair, a lace fan"),
  c("mexican", "calaverita", "Calaverita", "Sugar Skull", "Una calaverita de azúcar.", "A sugar skull.",
    "Sugar Skull, a cute sugar-skull character with colorful icing decorations, flower eyes, tiny arms and legs"),
  c("mexican", "pinata", "Piñata", "Piñata", "La piñata de la fiesta.", "The party piñata.",
    "Pinata, a classic seven-pointed star piñata character with colorful tissue paper and streamers, a face in the center"),
  c("mexican", "xolo", "Xólotl", "Xolo", "Un xoloitzcuintle sabio.", "A wise Xolo dog.",
    "Xolo, a hairless grey Xoloitzcuintle dog with big upright ears, a little tuft on the head, a colorful collar"),
  c("mexican", "lotero", "El Gallo", "The Rooster", "Una carta de lotería viva.", "A living lotería card.",
    "The Rooster, a proud cute rooster character inspired by the lotería card, red comb, colorful tail feathers, standing tall"),
  c("mexican", "frutero", "Don Fruta", "Fruit Man", "Fruta con chile y limón.", "Fruit with chili and lime.",
    "Fruit Man, a street fruit vendor with an apron and a cart umbrella hat, holding a cup of fruit with chili"),
  c("mexican", "danzante", "Danzante", "Aztec Dancer", "Un danzante con penacho.", "A dancer with a plumed headdress.",
    "Aztec Dancer, a concheros dancer with a colorful feathered headdress, ankle seed rattles, a decorated tunic"),
  c("mexican", "quetzal", "Quetzal", "Quetzal", "Un quetzal brillante.", "A brilliant quetzal.",
    "Quetzal, a resplendent quetzal bird with emerald-green feathers, a red belly, a long flowing tail"),
  c("mexican", "nopal", "Nopalito", "Nopalito", "Un nopal con tunas.", "A prickly pear cactus with fruit.",
    "Nopalito, a cute nopal cactus character made of rounded paddles with pink tuna fruits, a face, tiny arms"),
  c("mexican", "chapulin", "Chapulín", "Grasshopper", "Un chapulín saltarín.", "A hopping grasshopper.",
    "Grasshopper, a green chibi grasshopper with big eyes, long hopping legs, tiny antennae"),
  c("mexican", "tlaloc", "Lluvia", "Rainy", "Trae la lluvia buena.", "Brings the good rain.",
    "Rainy, a cute rain spirit inspired by pre-Hispanic art, round goggle eyes, a turquoise rain cloud crown, tiny rain drops"),
  c("mexican", "trajinera", "Xochi", "Xochi", "Paseando por Xochimilco.", "Cruising Xochimilco.",
    "Xochi, a girl with a flower crown holding a little painted wooden trajinera boat with painted flower decorations"),
  c("mexican", "matraca", "Matraca", "Matraca", "Hace ruido de fiesta.", "Makes party noise.",
    "Matraca, a colorful wooden matraca noisemaker character with painted flowers, a face, tiny arms and legs"),
  c("mexican", "cempasuchil", "Cempasúchil", "Marigold", "La flor del Día de Muertos.", "The Day of the Dead flower.",
    "Marigold, a cempasuchil marigold flower character with ruffled orange petals as hair, a green stem body, tiny leaf arms"),
  c("mexican", "pan-muerto", "Pan de Muerto", "Pan de Muerto", "Dulce tradición.", "A sweet tradition.",
    "Pan de Muerto, a round sugar-dusted pan de muerto bread character with bone-shaped decorations on top, a face, tiny arms and legs"),

  // Fantasy & myth.
  c("fantasy", "dragon", "Dragoncito", "Drako", "Un dragón pequeño pero fuerte.", "A small but mighty dragon.",
    "Drako, a baby dragon with green scales, small bat wings, a cream belly, tiny horns, a puff of smoke"),
  c("fantasy", "unicornio", "Unicornia", "Uni", "Un unicornio mágico.", "A magical unicorn.",
    "Uni, a white unicorn standing upright with a pastel rainbow mane, a golden spiral horn, sparkles"),
  c("fantasy", "mago", "Mago Merlín", "Wizard Merl", "Un mago sabio.", "A wise wizard.",
    "Wizard Merl, a little wizard with a long white beard, a starry blue pointed hat and robe, a glowing wand"),
  c("fantasy", "bruja", "Brujita", "Witchy", "Una brujita buena onda.", "A friendly little witch.",
    "Witchy, a friendly little witch with a purple pointed hat, a black dress, striped stockings, a broomstick"),
  c("fantasy", "hada", "Hada Lila", "Fairy Lila", "Un hada que cumple deseos.", "A fairy who grants wishes.",
    "Fairy Lila, a tiny fairy with translucent butterfly wings, a lilac petal dress, a sparkling wand"),
  c("fantasy", "sirena", "Marina", "Marina", "Una sirena del mar profundo.", "A mermaid from the deep sea.",
    "Marina, a mermaid with long teal hair, a seashell top, a shimmering turquoise tail, sitting upright"),
  c("fantasy", "robot", "Robi", "Robo", "Un robot amigable.", "A friendly robot.",
    "Robo, a round friendly robot with a screen face, an antenna, metal arms, a small heart light on the chest"),
  c("fantasy", "alien", "Zorg", "Zorg", "Un alien que viene en paz.", "An alien who comes in peace.",
    "Zorg, a little green alien with big black glossy eyes, two antennae, a silver jumpsuit"),
  c("fantasy", "fantasma", "Boo", "Boo", "Un fantasmita nada aterrador.", "A not-scary little ghost.",
    "Boo, a cute white sheet ghost with a wavy bottom, rosy cheeks, a tiny floating glow"),
  c("fantasy", "vampiro", "Conde Dracu", "Count Dracu", "Un vampiro vegetariano.", "A vegetarian vampire.",
    "Count Dracu, a cute little vampire with slicked-back hair, a high-collar black and red cape, tiny fangs, holding a tomato"),
  c("fantasy", "caballero", "Sir Valiente", "Sir Brave", "Un caballero noble.", "A noble knight.",
    "Sir Brave, a little knight in shiny armor with a red plume on the helmet, a shield, a wooden sword"),
  c("fantasy", "princesa", "Princesa Estrella", "Princess Star", "Una princesa valiente.", "A brave princess.",
    "Princess Star, a princess with a small golden star tiara, a flowing gown, holding a small bouquet, confident pose"),
  c("fantasy", "fenix", "Fénix", "Phoenix", "Siempre renace.", "Always rises again.",
    "Phoenix, a baby phoenix bird with flame-like red, orange and gold feathers, glowing ember sparkles"),
  c("fantasy", "yeti", "Yeti", "Yeti", "Un yeti abrazable.", "A huggable yeti.",
    "Yeti, a fluffy white yeti with blue-grey face and hands, small horns, a cozy scarf"),
  c("fantasy", "duende", "Duende", "Gnome", "Un duende del bosque.", "A forest gnome.",
    "Gnome, a garden gnome with a tall red pointed hat, a big white beard, a blue tunic, holding a mushroom"),
  c("fantasy", "pegaso", "Pegaso", "Pegasus", "Un caballo con alas.", "A winged horse.",
    "Pegasus, a small white winged horse standing upright, feathered wings, a light-blue mane"),
  c("fantasy", "kraken", "Kraky", "Kraky", "Un kraken muy tierno.", "A very cute kraken.",
    "Kraky, a purple baby kraken with curly tentacles, a tiny pirate hat, big shiny eyes"),
  c("fantasy", "ninja", "Ninja Sombra", "Ninja Shadow", "Un ninja silencioso.", "A silent ninja.",
    "Ninja Shadow, a chibi ninja in a dark navy outfit with a mask showing only the eyes, a headband, a toy throwing star"),
  c("fantasy", "pirata", "Capitán Barba", "Captain Beard", "Un pirata buscando tesoros.", "A pirate hunting treasure.",
    "Captain Beard, a little pirate with a tricorn hat, an eye patch, a striped shirt, a treasure map, a parrot on the shoulder"),
  c("fantasy", "genio", "Genio", "Genie", "Un genio de la lámpara.", "A genie from the lamp.",
    "Genie, a small friendly lilac-purple magic lamp spirit, a round body that tapers into a swirling smoke tail, a little turban with a jewel, holding a small brass oil lamp"),

  // Vehicles & space.
  c("space", "cohete", "Cohetín", "Rocky Rocket", "Un cohete listo para despegar.", "A rocket ready for liftoff.",
    "Rocky Rocket, a red and white rocket character with round windows as eyes, fins as feet, a small flame"),
  c("space", "planeta", "Saturnito", "Saturny", "Un planeta con anillos.", "A planet with rings.",
    "Saturny, a small orange planet character with a tilted ring, a face, tiny arms and feet"),
  c("space", "estrella", "Estrellita", "Twinkle", "Una estrella que brilla.", "A twinkling star.",
    "Twinkle, a glowing yellow five-pointed star character with a face, tiny arms and legs"),
  c("space", "lunita", "Lunita", "Moony", "Una luna que te cuida de noche.", "A moon who watches over you at night.",
    "Moony, a crescent moon character in a sleeping cap, a face, tiny arms"),
  c("space", "sol", "Solecito", "Sunny", "Un sol que calienta tu día.", "A sun that warms your day.",
    "Sunny, a round smiling sun with rays, wearing tiny sunglasses, tiny arms and legs"),
  c("space", "cometa", "Cometa", "Comet", "Una cometa veloz.", "A speedy comet.",
    "Comet, a glowing icy-blue comet character with a long sparkly tail, a face, tiny arms"),
  c("space", "ovni", "Ovni", "UFO", "Un platillo volador amistoso.", "A friendly flying saucer.",
    "UFO, a silver flying saucer with a glass dome, colorful lights around the rim, a face on the dome"),
  c("space", "satelite", "Sateli", "Sat", "Un satélite que conecta al mundo.", "A satellite connecting the world.",
    "Sat, a small satellite character with blue solar panel wings, an antenna, a face on its body"),
  c("space", "astronauta-perro", "Laika", "Laika", "Una perrita astronauta.", "A space puppy.",
    "Laika, a little dog astronaut in a white space suit with a round clear bubble helmet"),
  c("space", "carro", "Carrito", "Zoom", "Un carro de carreras.", "A race car.",
    "Zoom, a small round go-kart character in teal and yellow, big round headlights as the eyes on the front bumper, a grille smile, chunky wheels, no windshield eyes, no numbers"),
  c("space", "camion", "Camioncito", "Trucky", "Un camión trabajador.", "A hardworking truck.",
    "Trucky, a yellow dump truck character with headlights as eyes, a smiling bumper, chunky wheels"),
  c("space", "tren", "Trenecito", "Choo", "Un tren que va a todos lados.", "A train that goes everywhere.",
    "Choo, a tiny chubby toy steam locomotive in green and gold, puffing a heart-shaped cloud, two round lamp eyes on the cab windows, a smile on the cowcatcher, no face on the smokebox front"),
  c("space", "avion", "Avioncito", "Jetty", "Un avión que vuela alto.", "A plane that flies high.",
    "Jetty, a small white and blue airplane character with a face on the nose, wings as arms"),
  c("space", "barco", "Barquito", "Boaty", "Un barco navegante.", "A seafaring boat.",
    "Boaty, a little red and white tugboat character with a smokestack, porthole eyes, a life ring"),
  c("space", "helicoptero", "Heli", "Heli", "Un helicóptero de rescate.", "A rescue helicopter.",
    "Heli, a small orange rescue helicopter character with spinning rotor, a windshield face"),
  c("space", "submarino", "Submarino", "Subby", "Explora el fondo del mar.", "Explores the deep sea.",
    "Subby, a yellow submarine character with round porthole eyes, a periscope, little bubbles"),
  c("space", "moto", "Moto", "Vroom", "Una moto veloz.", "A speedy motorbike.",
    "Vroom, a sleek blue motorcycle character with a headlight eye, handlebars as arms"),
  c("space", "bici", "Bicicleta", "Bikey", "Una bici paseadora.", "A cruising bike.",
    "Bikey, a mint-green vintage bicycle character with a basket of flowers, a face on the front basket"),
  c("space", "agujero-negro", "Hoyo Negro", "Black Hole", "Un agujero negro con mucha atracción.", "A very attractive black hole.",
    "Black Hole, a cute round dark purple swirling black hole character with a glowing purple accretion ring, a face"),
  c("space", "tierra", "Tierrita", "Earthy", "Nuestro planeta azul.", "Our blue planet.",
    "Earthy, a small planet Earth character with blue oceans, green continents, a little cloud, a face, tiny arms and legs"),

  // Seasons & holidays.
  c("seasons", "santa", "Santa", "Santa", "Trae regalos todo el año.", "Brings gifts all year.",
    "Santa, a chibi Santa Claus with a big white beard, a red suit with white fur trim, a gift sack"),
  c("seasons", "reno", "Reno", "Reindeer", "Un reno de nariz roja.", "A red-nosed reindeer.",
    "Reindeer, a baby reindeer with brown fur, antlers, a shiny red nose, a jingle bell collar"),
  c("seasons", "muneco-nieve", "Muñeco de Nieve", "Snowy", "Un muñeco de nieve amigable.", "A friendly snowman.",
    "Snowy, a snowman with a carrot nose, coal buttons, a red scarf, a top hat, stick arms"),
  c("seasons", "elfo", "Elfo", "Elf", "Ayudante de Santa.", "Santa's helper.",
    "Elf, a Christmas elf in a green outfit with a pointed hat with a bell, pointy ears, curled shoes"),
  c("seasons", "calabaza", "Calabacita", "Pumpkin", "Una calabaza de Halloween.", "A Halloween pumpkin.",
    "Pumpkin, a cute jack-o-lantern pumpkin character with a friendly carved face, a green stem, tiny arms and legs"),
  c("seasons", "momia", "Momia", "Mummy", "Una momia muy tierna.", "A very cute mummy.",
    "Mummy, a cute chibi mummy wrapped in loose bandages with one big eye peeking out, tiny arms"),
  c("seasons", "conejo-pascua", "Conejo de Pascua", "Easter Bunny", "Esconde huevos de colores.", "Hides colorful eggs.",
    "Easter Bunny, a pastel bunny holding a basket of painted eggs, a bow tie"),
  c("seasons", "cupido", "Cupido", "Cupid", "Flechazos de amor.", "Arrows of love.",
    "Cupid, a chubby baby cupid with small white wings, a heart-tipped bow and arrow"),
  c("seasons", "pavo", "Pavito", "Turkey", "Agradecido por todo.", "Thankful for everything.",
    "Turkey, a round turkey with a fan of colorful tail feathers, a pilgrim hat"),
  c("seasons", "trebol", "Trébol", "Clover", "Te trae buena suerte.", "Brings you good luck.",
    "Clover, a little leprechaun-style character in green with a top hat and a four-leaf clover"),
  c("seasons", "primavera", "Primavera", "Spring", "Florece con la primavera.", "Blooms with spring.",
    "Spring, a flower-fairy girl with a crown of blossoms, a dress made of petals, a butterfly on her hand"),
  c("seasons", "verano", "Verano", "Summer", "Siempre de vacaciones.", "Always on vacation.",
    "Summer, a beachgoer with sunglasses, a floral shirt, swim trunks, an inflatable ring, a beach ball"),
  c("seasons", "otono", "Otoño", "Autumn", "Entre hojas que caen.", "Among falling leaves.",
    "Autumn, a kid in a cozy orange sweater and scarf, holding a pumpkin spice drink, falling maple leaves around"),
  c("seasons", "invierno", "Invierno", "Winter", "Bien abrigadito.", "All bundled up.",
    "Winter, a kid bundled up in a puffy blue coat, earmuffs, mittens, a snowflake on the mitten"),
  c("seasons", "ano-nuevo", "Año Nuevo", "New Year", "¡Feliz año nuevo!", "Happy New Year!",
    "New Year, a party character in a sparkly gold outfit and party hat, holding a sparkler, confetti around"),
  c("seasons", "rosca", "Rosca de Reyes", "Rosca", "Ojalá no te salga el niño.", "Hope you don't get the baby.",
    "Rosca, a round rosca de reyes sweet bread character with colorful candied fruit, a face, tiny arms and legs"),
  c("seasons", "rey-mago", "Rey Mago", "Wise King", "Trae regalos el 6 de enero.", "Brings gifts on January 6th.",
    "Wise King, one of the three wise kings in a jeweled crown and a purple velvet robe, holding a small gift box"),
  c("seasons", "posada", "Posadita", "Posada", "Lista para la posada.", "Ready for the posada.",
    "Posada, a kid holding a small lit candle and a paper lantern, a cozy poncho, Christmas posada spirit"),
  c("seasons", "pino", "Pinito", "Pine", "Un arbolito de navidad.", "A little Christmas tree.",
    "Pine, a small Christmas tree character with ornaments, a star on top, a face, tiny arms and legs"),
  c("seasons", "regalo", "Regalito", "Gifty", "Una sorpresa envuelta.", "A wrapped surprise.",
    "Gifty, a wrapped gift box character with a big red bow on top, a face, tiny arms and legs"),
];
